### GET request to read all admin users
GET http://localhost:3000/api/v1/admin

### POST request to create a new user
POST http://localhost:3000/api/v1/admin/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "test123456",
  "role": "admin"
}

### DELETE request to delete a user
DELETE http://localhost:3000/api/v1/tenants/2

### POST Login a user
POST http://localhost:3000/api/v1/admin/auth/cookie/login
Content-Type: application/json

{
    "email": "alice@example.com",
    "password" : "password123"
}

### POST Logout a user
POST http://localhost:3000/api/v1/admin/auth/cookie/logout

### GET check user authentication
GET http://localhost:3000/api/v1/admin/auth/cookie/me


